name: CustomItemsPlugin
version: '1.0-SNAPSHOT'
main: org.awayxd.defaultCustomWepons.CustomItemsPlugin
api-version: '1.21'
commands:
  givecustomitem:
    description: Gives a custom item to a player
    usage: /<command> <item> <player>
